BEGIN;

ALTER TABLE "bonos_tickets_horas"
  DROP COLUMN IF EXISTS "nroTicket",
  DROP COLUMN IF EXISTS "asunto",
  DROP COLUMN IF EXISTS "tipo",
  ADD COLUMN IF NOT EXISTS "cumplimientoTickets" INTEGER,
  ADD COLUMN IF NOT EXISTS "cumplimientoTotal" INTEGER,
  ADD COLUMN IF NOT EXISTS "cumplimientoPct" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "calidadTickets" INTEGER,
  ADD COLUMN IF NOT EXISTS "calidadTotal" INTEGER,
  ADD COLUMN IF NOT EXISTS "calidadPct" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "horasConTicket" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "horasSinTicket" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "horasInternas" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "horasNoLaborales" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "horasTotales" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "fechaCargaHoras" TIMESTAMP(3);

ALTER TABLE "bonos_recibos_sueldo"
  ADD COLUMN IF NOT EXISTS "sueldoNeto" INTEGER NOT NULL DEFAULT 0;

COMMIT;
